### ISSUE TITLE
TriggerBatch with interface{} instead of string for Data field

### ISSUE THREAD

**Issue by mikefaraponov** [pusher/pusher-http-go#52]
TriggerBatch with interface{} instead of string for Data field of pusher.Event structure

**Comment by damdo** [comment]
Thank you for getting in touch @mikefaraponov 
What you are referring to might be already there:
https://github.com/pusher/pusher-http-go/blob/master/client.go#L211-L226

We introduced it with this PR: https://github.com/pusher/pusher-http-go/pull/51
and it has been released since the [2.0.0 Release](https://github.com/pusher/pusher-http-go/releases/tag/v2.0.0)

Let me know if this solves you issue

**Comment by mikefaraponov** [comment]
Thx, yes, I saw it
