### ISSUE TITLE
Suggestion: expose function to manually pass channel name and socket ID for authentication

### ISSUE THREAD

**Issue by philippfrank** [pusher/pusher-http-go#72]
If I'm correct, `AuthenticatePrivateChannel` is the only way to compute the auth token.

Other official libraries, include something like:

```js
var auth = pusher.authenticate(socketId, channel);
```

See: https://github.com/pusher/pusher-http-node#authenticating-private-channels

Right now, if I want to perform some basic checks on the channel name, I need to replicate the byte parsing logic that `AuthenticatePrivateChannel` does internally in https://github.com/pusher/pusher-http-go/blob/61fc56dfae01b9f01fa4e5c4cf60ba89e306c9f4/util.go#L20

**Comment by ben-pusher** [comment]
If I understand correctly you are looking for access to the channel name and socket id directly, rather than just blindly passing them to the built in auth mechanism - is this correct? 
The client will send these values as the request body sent to the auth endpoint, so you should be able to achieve this.  
Using the example at https://github.com/pusher/pusher-http-go#func-c-client-authenticateprivatechannel you can see that these values are retrieved from the req.Body and stored as the params variable that is then passed to AuthenticatePrivateChannel. You should be able to access and check these params and then move to the authentication step only once happy the channel name is correct. 

`func pusherAuth(res http.ResponseWriter, req *http.Request) {
   //get the channel name and the socket id from the request body
 params, _ := ioutil.ReadAll(req.Body)
    response, err := pusherClient.AuthenticatePrivateChannel(params)
    if err != nil {
        panic(err)
    }

    fmt.Fprintf(res, string(response))
}

func main() {
    http.HandleFunc("/pusher/auth", pusherAuth)
    http.ListenAndServe(":5000", nil)
}`

**Comment by philippfrank** [comment]
Thanks for the reply, but no. As I wrote, I am looking for a way to _pass_ socket ID and channel name manually. In the official pusher node client (which I linked above) that is possible. It would allow users to construct custom payloads.
